"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def fib(n):
    '''Fetches next Fibonacci sequence number recursively'''
    if n <= 2:
        return n
    else:
        return  fib(n-2) + fib(n-1)

def main():
    '''By considering the terms in the Fibonacci sequence
    whose values do not exceed four million, 
    find the sum of the even-valued terms.
    '''
    f = True
    i = 1
    sum_fib = 0
    while f == True:
        fibonacci = fib(i)
        i += 1
        
        if fibonacci > 4000000:
            f = False
        
        if fibonacci % 2 == 0:
            sum_fib += fibonacci
            
    print(sum_fib)
    
main()